---
permalink: online-help/concept-storage-vm-performance-explorer-page.html 
sidebar: sidebar 
keywords:  
summary: 'La pagina Performance/SVM Explorer (Esplora prestazioni/SVM) fornisce una panoramica dettagliata delle performance di tutte le macchine virtuali di storage in un cluster.' 
---
= Pagina Storage VM/Performance Explorer
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La pagina Performance/SVM Explorer (Esplora prestazioni/SVM) fornisce una panoramica dettagliata delle performance di tutte le macchine virtuali di storage (SVM) in un cluster.

La pagina Storage VM/Performance consente di tenere traccia e confrontare le performance di SVM durante un periodo di tempo specifico, che consente di eseguire il troubleshooting e di ottimizzare le performance di SVM.

Utilizzando la funzionalità View and compare è possibile confrontare le performance di questa Storage VM con:

* Altre SVM sullo stesso cluster
* I volumi su questa SVM
* Le interfacce di rete su questa SVM


La pagina Storage VM/Performance consente di:

* Visualizza i problemi relativi alle soglie e i relativi dettagli
* Monitora e confronta i dati delle performance SVM
* Analizzare e risolvere i problemi relativi alla soglia
* Analizzare e risolvere i problemi relativi alle prestazioni

