---
permalink: online-help/concept-managing-storage-efficiency-policies.html 
sidebar: sidebar 
keywords: add 
summary: 'Una policy sull"efficienza dello storage consente di definire le caratteristiche di efficienza dello storage di un workload. È possibile assegnare una policy di efficienza dello storage a un workload durante la creazione iniziale del workload o successivamente modificando il workload.' 
---
= Gestione delle policy di efficienza dello storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una Storage Efficiency Policy (SEP) consente di definire le caratteristiche di efficienza dello storage di un workload. È possibile assegnare una policy di efficienza dello storage a un workload durante la creazione iniziale del workload o successivamente modificando il workload.

L'efficienza dello storage include l'utilizzo di tecnologie come thin provisioning, deduplica e compressione dei dati che aumentano l'utilizzo dello storage e riducono i costi dello storage. Durante la creazione delle policy di efficienza dello storage, è possibile utilizzare queste tecnologie per risparmiare spazio singolarmente o insieme per ottenere la massima efficienza dello storage. Quando si associano le policy ai carichi di lavoro dello storage, vengono assegnate loro le impostazioni di policy specificate. Unified Manager consente di assegnare policy di efficienza dello storage definite dal sistema e definite dall'utente per ottimizzare le risorse di storage nel data center.

Unified Manager offre due policy di efficienza dello storage definite dal sistema: Alta e bassa. Questi SEPS sono applicabili alla maggior parte dei carichi di lavoro dello storage in un data center; tuttavia, è possibile creare policy personalizzate se i SEPS definiti dal sistema non soddisfano i requisiti.

Non è possibile modificare una policy di efficienza dello storage definita dal sistema o attualmente assegnata a un workload. Non è possibile eliminare una policy di efficienza dello storage assegnata a un workload o se è l'unica policy di efficienza dello storage disponibile.

La pagina Storage Efficiency Policies (Criteri di efficienza dello storage) elenca le policy di efficienza dello storage disponibili e consente di aggiungere, modificare ed eliminare SEPS personalizzati. In questa pagina vengono visualizzate le seguenti informazioni:

[cols="1a,1a"]
|===
| Campo | Descrizione 


 a| 
Nome
 a| 
Nome della policy di efficienza dello storage.



 a| 
Tipo
 a| 
Se il criterio è definito dal sistema o dall'utente.



 a| 
Riserva di spazio
 a| 
Se il volume è dotato di thin provisioning o thick provisioning.



 a| 
Deduplica
 a| 
Se la deduplica è attivata sul volume:

* `Inline`: La deduplica si verifica durante la scrittura sul volume
* `Background`: La deduplica avviene in background
* `Disable`: La deduplica è disattivata sul volume




 a| 
Compressione
 a| 
Se la compressione dei dati è attivata sul volume:

* `Inline`: La compressione dei dati si verifica durante la scrittura sul volume
* `Background`: La compressione dei dati avviene in background
* `Disable`: La compressione dei dati è disattivata sul volume




 a| 
Carichi di lavoro
 a| 
Numero di carichi di lavoro dello storage a cui è stata assegnata la Storage Efficiency Policy

|===


== Linee guida per la creazione di una policy di efficienza dello storage personalizzata

Se le policy di efficienza dello storage esistenti non soddisfano i requisiti delle policy per i carichi di lavoro dello storage, è possibile creare una policy di efficienza dello storage personalizzata. Tuttavia, si consiglia di tentare di utilizzare le policy di efficienza dello storage definite dal sistema per i carichi di lavoro dello storage e di creare policy di efficienza dello storage personalizzate solo se necessario.
