---
permalink: online-help/reference-dashboard-page.html 
sidebar: sidebar 
keywords: Dashboard 
summary: 'La pagina Dashboard contiene "pannelli" che visualizzano l"elevato livello di capacità, performance e sicurezza dei cluster monitorati. Questa pagina fornisce anche un pannello azioni di gestione che elenca le correzioni che Unified Manager può apportare per risolvere determinati eventi.' 
---
= Pagina del dashboard
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nella pagina Dashboard sono presenti "`panels`" che mostrano l'elevato livello di capacità, performance e sicurezza dei cluster monitorati. Questa pagina fornisce anche un pannello azioni di gestione che elenca le correzioni che Unified Manager può apportare per risolvere determinati eventi.

La maggior parte dei pannelli visualizza anche il numero di eventi attivi in tale categoria e il numero di nuovi eventi aggiunti nelle 24 ore precedenti. Queste informazioni consentono di decidere quali cluster è necessario analizzare ulteriormente per risolvere gli eventi. Facendo clic sugli eventi vengono visualizzati gli eventi principali e viene fornito un collegamento alla pagina dell'inventario Gestione eventi filtrata per visualizzare gli eventi attivi in tale categoria.

Nella parte superiore della dashboard è possibile scegliere se visualizzare le informazioni per tutti i cluster monitorati o per un singolo cluster. È possibile iniziare visualizzando lo stato di tutti i cluster e quindi eseguire il drill-down dei singoli cluster quando si desidera visualizzare informazioni dettagliate.

[NOTE]
====
Alcuni dei pannelli elencati di seguito potrebbero non essere visualizzati nella pagina in base alla configurazione.

====
* *Pannello azioni di gestione*
+
Unified Manager può diagnosticare accuratamente alcuni problemi e fornire una singola soluzione. Quando disponibili, queste risoluzioni vengono visualizzate in questo pannello con il pulsante *Correggi*. È possibile risolvere questi problemi immediatamente da Unified Manager invece di dover utilizzare Gestione di sistema di ONTAP o l'interfaccia utente di ONTAP.

+
Vedere link:concept-fixing-ontap-issues-directly-from-unified-manager.html["Risoluzione dei problemi di ONTAP direttamente da Unified Manager"] per ulteriori informazioni.

* *Pannello capacità*
+
Durante la visualizzazione di tutti i cluster, questo pannello visualizza la capacità fisica totale e la capacità logica utilizzata per ciascun cluster, il numero di giorni in cui i dischi sono stati progettati per essere pieni e il rapporto di riduzione dei dati in base alle impostazioni di efficienza dello storage ONTAP configurate. Inoltre, elenca la capacità utilizzata per qualsiasi Tier cloud configurato. Facendo clic sul grafico a barre si accede alla pagina di inventario degli aggregati per quel cluster. Facendo clic sul testo "`Days to Full`" (Invia a tutto) viene visualizzato un messaggio che identifica l'aggregato con il numero minimo di giorni di capacità rimanenti; fare clic sul nome dell'aggregato per visualizzare ulteriori dettagli.

+
Durante la visualizzazione di un singolo cluster, questo pannello visualizza la capacità fisica totale e la capacità logica utilizzata per gli aggregati di dati ordinati per ciascun tipo di disco nel Tier locale e per il Tier cloud. Facendo clic sul grafico a barre di un tipo di disco, si accede alla pagina di inventario dei volumi per i volumi che utilizzano quel tipo di disco.

* *Pannello Performance Capacity*
+
Durante la visualizzazione di tutti i cluster, questo pannello visualizza il valore della capacità delle performance per ciascun cluster (media nell'ora precedente) e il numero di giorni fino a quando la capacità delle performance non raggiunge il limite massimo (in base al tasso di crescita giornaliero). Facendo clic sul grafico a barre si accede alla pagina di inventario dei nodi per quel cluster. Si noti che la pagina di inventario dei nodi visualizza la capacità di performance media nelle 72 ore precedenti, pertanto questo valore potrebbe non corrispondere al valore del Dashboard. Facendo clic sul testo "`Days to Full`" (Invia a tutto) viene visualizzato un messaggio che identifica il nodo con il numero minimo di giorni di capacità delle performance rimanenti; fare clic sul nome del nodo per visualizzare ulteriori dettagli.

+
Durante la visualizzazione di un singolo cluster, questo pannello visualizza i valori di capacità delle performance del cluster, IOPS totali e throughput totale (MB/s) e il numero di giorni in cui ciascuna di queste tre metriche deve raggiungere il limite massimo.

* *Pannello workload IOPS*
+
Questo pannello visualizza il numero totale di carichi di lavoro attualmente in esecuzione in un determinato intervallo di IOPS e divide il numero in base ai tipi di disco.

* *Pannello workload Performance*
+
Questo pannello visualizza il numero totale di carichi di lavoro conformi e non conformi assegnati a ciascun livello di servizio delle performance definito. Visualizza anche il numero di workload a cui non è assegnato un PSL. Facendo clic su un grafico a barre, è possibile accedere ai carichi di lavoro assegnati a tale policy nella pagina carichi di lavoro.

* *Pannello di sicurezza*
+
Quando si visualizzano tutti i cluster, questo pannello visualizza il numero di cluster conformi o non conformi, il numero di SVM conformi o non conformi e il numero di volumi crittografati o non crittografati. La conformità è basata su https://www.netapp.com/pdf.html?item=/media/10674-tr4569pdf.pdf["Guida al rafforzamento della sicurezza di NetApp per ONTAP 9"^]. Fare clic sulla freccia destra nella parte superiore del pannello per visualizzare i dettagli di sicurezza per tutti i cluster nella pagina Security (sicurezza).

+
Durante la visualizzazione di un singolo cluster, questo pannello visualizza se il cluster è conforme o meno, il numero di SVM conformi o non conformi e il numero di volumi crittografati o non crittografati. Fare clic sulla freccia destra nella parte superiore del pannello per visualizzare i dettagli di sicurezza del cluster nella pagina Security (sicurezza).

* *Pannello Usage Overview (Panoramica utilizzo)*
+
Durante la visualizzazione di tutti i cluster, è possibile scegliere di visualizzare i cluster in base agli IOPS più elevati, al throughput più elevato (MB/s) o alla capacità fisica più elevata utilizzata.

+
Durante la visualizzazione di un singolo cluster, è possibile scegliere di visualizzare i carichi di lavoro in base agli IOPS più elevati, al throughput più elevato (MB/s) o alla capacità fisica più elevata utilizzata.


