---
permalink: online-help/task-exporting-storage-data-as-reports.html 
sidebar: sidebar 
keywords:  
summary: 'È possibile esportare i dati in un file .csv o in un documento .pdf separato da virgole e utilizzare i dati esportati per creare i report. Ad esempio, se sono presenti 10 eventi critici che non sono stati risolti, è possibile esportare i dati dalla pagina dell"inventario di gestione degli eventi per creare un report e quindi intraprendere l"azione appropriata.' 
---
= Esportazione di dati in file CSV e PDF per la creazione di report
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile esportare i dati in valori separati da virgole (`.csv`) o. (`.pdf`) e utilizzare i dati esportati per creare report. Ad esempio, se sono presenti 10 eventi critici che non sono stati risolti, è possibile esportare i dati dalla pagina dell'inventario di gestione degli eventi per creare un report e quindi intraprendere l'azione appropriata.



== A proposito di questa attività

È possibile esportare i dati in un `.csv` file o. `.pdf` Documenta dalle pagine di inventario Storage, Network e Quality of Service e utilizza i dati esportati per creare report.



== Fasi

. Eseguire una delle seguenti operazioni:
+
[cols="1a,1a"]
|===
| Se si desidera esportare... | Eseguire questa operazione... 


 a| 
Dettagli dell'evento
 a| 
Fare clic su *Event Management* (Gestione eventi) dal menu di navigazione a sinistra.



 a| 
Dettagli dell'inventario degli oggetti di storage
 a| 
Fare clic su *Storage* o *Network* dal menu di navigazione a sinistra, quindi selezionare un oggetto di storage. Quindi scegliere una delle viste *Health*, *Capacity*, *Performance* o *Relationship*.



 a| 
Dettagli sulla capacità dello storage e sulla cronologia della protezione
 a| 
Fare clic su *Storage* > *Aggregates* o *Storage* > *Volumes*, quindi selezionare un singolo aggregato o volume.



 a| 
Primi 10 dettagli sulle performance dell'oggetto storage
 a| 
Fare clic su *Storage* > *Clusters* > *Performance/All Clusters*, quindi selezionare un cluster e scegliere la scheda *Top Performers*. Quindi selezionare un oggetto di storage e un contatore delle performance.



 a| 
Dettagli del gruppo di policy QoS
 a| 
Fare clic su *Storage* > *QoS Policy Groups* (gruppi policy QoS) dal menu di navigazione a sinistra.

|===
. Fare clic sul pulsante *Export* (Esporta).
. Fare clic su *CSV file* o *PDF Document* per confermare la richiesta di esportazione.
+
Dalla scheda Top Performer è possibile scegliere di scaricare un report delle statistiche per il singolo cluster visualizzato o per tutti i cluster del data center.

+
Il file viene scaricato.

. Aprire `.csv` file o. `.pdf` documentare nell'applicazione appropriata.

