---
settings:
  name: Active IQ Unified Manager 9.7
  downlevel: true
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - version-number: '9.7'
    url: "/active-iq-unified-manager-97"
  - version-number: '9.9'
    url: "/active-iq-unified-manager-99"
  - version-number: '9.8'
    url: "/active-iq-unified-manager-98"
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documenti di Active IQ Unified Manager 9.7
    url: "/index.html"
  - title: Note di rilascio
    url: "/release-notes.html"
  - title: Inizia subito
    entries:
    - title: Installazione rapida per VMware vSphere
      url: "/install-vapp/qsg-vapp.html"
    - title: Installazione rapida per Linux
      url: "/install-linux/qsg-linux.html"
    - title: Installazione rapida per Windows
      url: "/install-windows/qsg-windows.html"
  - section: install-vapp
  - section: install-linux
  - section: install-windows
  - section: config
  - section: online-help
  - section: performance-checker
  - section: health-checker
  - section: data-protection
  - section: reporting
  - section: api-automation
  - title: Note legali
    url: "/reference-legal-notices.html"
homepage:
  tiles:
  - title: Inizia subito
    links:
    - title: Note di rilascio
      url: "/release-notes.html"
    - title: Installazione rapida per VMware vSphere
      url: "/install-vapp/qsg-vapp.html"
    - title: Installazione rapida per Linux
      url: "/install-linux/qsg-linux.html"
    - title: Installazione rapida per Windows
      url: "/install-windows/qsg-windows.html"
  - title: Installare e configurare Unified Manager
    links:
    - title: Installazione e aggiornamento su sistemi VMware vSphere
      url: "/install-vapp/concept-requirements-for-installing-unified-manager.html"
    - title: Installazione e aggiornamento su sistemi Linux
      url: install-linux/concept-requirements-for-installing-unified-manager.html
    - title: Installazione e aggiornamento su sistemi Windows
      url: "/install-windows/concept-requirements-for-installing-unified-manager.html"
    - title: Configurare Unified Manager
      url: "/config/concept-configuring-unified-manager.html"
  - title: Monitoraggio delle performance
    links:
    - title: Soglie di performance
      url: "/performance-checker/concept-managing-performance-thresholds.html"
    - title: Performance del cluster
      url: performance-checker/concept-monitoring-cluster-performance-from-the-dashboard.html
    - title: Gruppo di criteri QoS
      url: "/performance-checker/concept-managing-performance-using-qos-policy-group-information.html"
    - title: Workload Analyzer
      url: "/performance-checker/concept-troubleshooting-workloads-using-the-workload-analyzer.html"
    - title: Performance del carico di lavoro
      url: "/performance-checker/concept-collecting-data-and-monitoring-workload-performance.html"
    - title: Gestire le performance
      url: performance-checker/concept-managing-performance-using-perf-capacity-and-available-iops-information.html
  - title: Monitoraggio dello storage e dello stato degli oggetti
    links:
    - title: Integrità dei cluster e degli oggetti del cluster
      url: online-help/concept-managing-and-monitoring-clusters-and-cluster-object-health.html
    - title: Soglie di integrità
      url: "/health-checker/concept-managing-health-thresholds.html"
    - title: Invia messaggi AutoSupport e pacchetti di supporto
      url: health-checker/task-send-a-support-bundle-to-technical-support.html
  - title: Monitoraggio della protezione dei dati
    links:
    - title: Impostare la relazione di protezione
      url: "/data-protection/task-setting-up-protection-relationships-in-unified-manager.html"
    - title: Eseguire failover e failback
      url: data-protection/task-performing-a-protection-relationship-failover-and-failback.html
    - title: Gestire la relazione di protezione
      url: data-protection/concept-managing-and-monitoring-protection-relationships.html
    - title: Generare report
      url: "/reporting/concept-unified-manager-reporting.html"
  - title: Utilizzare API REST
    links:
    - title: Inizia subito
      url: "/api-automation/concept-api-url-and-categories.html"
    - title: Gestire gli oggetti storage
      url: "/api-automation/concept-data-center-apis.html"
    - title: Accedere alle API di ONTAP
      url: "/api-automation/concept-gateway-apis.html"
    - title: Flussi di lavoro comuni
      url: "/api-automation/concept-workflow-intro.html"
    - title: Eseguire il provisioning dello storage
      url: api-automation/concept-provisioning-workflow.html
  - title: Più risorse
    links:
    - title: Video di Unified Manager
      url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7mp3jFSg0IJgo3oeDQRY-Gl
    - title: Blog di Unified Manager
      url: https://www.netapp.com/blog/#q=active%20iq%20unified%20manager&t=Blogs&sort=%40publish_date_mktg%20descending&layout=card&f:@facet_language_mktg=[English]
    - title: Documentazione per la versione più recente di Active IQ Unified Manager
      url: https://docs.netapp.com/us-en/active-iq-unified-manager/index.html
