---
permalink: api-automation/concept-managing-lun.html 
sidebar: sidebar 
keywords:  
summary: È possibile utilizzare le API elencate qui per visualizzare, aggiungere ed eliminare LUN sulle macchine virtuali di storage. È inoltre possibile assegnare e modificare le policy di performance service level e di efficienza dello storage per le LUN. 
---
= Gestione delle LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare le API elencate di seguito per visualizzare, aggiungere ed eliminare LUN sulle macchine virtuali di storage (VM di storage). È inoltre possibile assegnare e modificare le policy di performance service level e di efficienza dello storage per le LUN.

Prima di assegnare lo storage, è necessario assicurarsi che la SVM sia stata creata e fornita con i protocolli supportati. Allo stesso modo, per assegnare i livelli di Performance Service alle LUN, è necessario creare i livelli di Performance Service prima di creare la LUN.



== Visualizza LUN

È possibile utilizzare il seguente metodo per visualizzare tutte le LUN nell'ambiente Unified Manager. Una volta aggiunto un cluster ONTAP come origine dati su Active IQ Unified Manager, i carichi di lavoro dello storage per tali cluster vengono aggiunti automaticamente all'istanza di Unified Manager. Questa API recupera tutti i LUN automaticamente e aggiunti manualmente all'istanza di Unified Manager. È possibile visualizzare i dettagli di un LUN specifico eseguendo questa API con la chiave LUN.

[cols="1a,1a,1a"]
|===
| Categoria | Verbo HTTP | Percorso 


 a| 
provider di storage
 a| 
OTTIENI
 a| 
`/storage-provider/luns`

`+/storage-provider/luns/{key}+`

|===


== Aggiungere LUN

È possibile utilizzare il seguente metodo per aggiungere LUN alle SVM.

[cols="1a,1a,1a"]
|===
| Categoria | Verbo HTTP | Percorso 


 a| 
provider di storage
 a| 
POST
 a| 
`/storage-provider/luns`

|===
[NOTE]
====
Nella richiesta di curl, se si fornisce un valore per il parametro opzionale `volume_name_tag` Nell'input, tale valore viene utilizzato durante la creazione del LUN. Questo tag consente di eseguire ricerche nel volume in modo semplice. Se si specifica il tasto volume nella richiesta, il tagging viene ignorato.

====


== Elimina LUN

Per eliminare una LUN specifica, utilizzare il metodo seguente. Per eliminare una determinata LUN, è necessario fornire la chiave LUN.

[NOTE]
====
Se è stato creato un volume in ONTAP e poi eseguito il provisioning delle LUN tramite Unified Manager su tale volume, quando si eliminano tutte le LUN utilizzando questa API, il volume viene eliminato anche dal cluster ONTAP.

====
[cols="1a,1a,1a"]
|===
| Categoria | Verbo HTTP | Percorso 


 a| 
provider di storage
 a| 
ELIMINARE
 a| 
`+/storage-provider/luns/{key}+`

|===


== Modificare i LUN

È possibile utilizzare il seguente metodo per modificare un LUN e aggiornarne le proprietà. Per modificare una determinata LUN, è necessario fornire la chiave LUN. È inoltre necessario immettere la proprietà LUN che si desidera aggiornare, insieme al relativo valore. Per aggiornare gli array LUN utilizzando questa API, consultare le raccomandazioni in "`Recommendations for Using the API`".

[NOTE]
====
È possibile aggiornare solo una proprietà a una singola chiamata di questa API. Per gli aggiornamenti multipli, è necessario eseguire questa API tante volte.

====
[cols="1a,1a,1a"]
|===
| Categoria | Verbo HTTP | Percorso 


 a| 
provider di storage
 a| 
PATCH
 a| 
`+/storage-provider/luns/{key}+`

|===