---
permalink: api-automation/concept-managing-fileshares-api.html 
sidebar: sidebar 
keywords:  
summary: È possibile utilizzare le API elencate di seguito per visualizzare, aggiungere ed eliminare condivisioni CIFS e condivisioni file NFS. Utilizzando queste API, è anche possibile assegnare e modificare i criteri di efficienza dello storage e del livello di servizio delle performance per le condivisioni di file. 
---
= Gestione delle condivisioni di file
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare le API elencate di seguito per visualizzare, aggiungere ed eliminare condivisioni CIFS e condivisioni file NFS. Utilizzando queste API, è anche possibile assegnare e modificare i criteri di efficienza dello storage e del livello di servizio delle performance per le condivisioni di file.

Prima di assegnare lo storage, la macchina virtuale deve essere stata creata e dotata dei protocolli supportati. Allo stesso modo, per assegnare le policy di efficienza dello storage alle condivisioni di file, è necessario creare le policy di efficienza dello storage prima di creare le condivisioni di file.



== Visualizzare le condivisioni di file

È possibile utilizzare il seguente metodo per visualizzare tutti i carichi di lavoro dello storage disponibili nel proprio ambiente Unified Manager. Una volta aggiunto un cluster ONTAP come origine dati su Active IQ Unified Manager, i carichi di lavoro dello storage per tali cluster vengono aggiunti automaticamente all'istanza di Unified Manager. Questa API recupera automaticamente tutte le condivisioni di file e le aggiunge manualmente all'istanza di Unified Manager. È possibile visualizzare i dettagli di una condivisione file specifica eseguendo questa API con la chiave di condivisione file.

[cols="1a,1a,1a"]
|===
| Categoria | Verbo HTTP | Percorso 


 a| 
provider di storage
 a| 
OTTIENI
 a| 
`/storage-provider/file-shares`

`+/storage-provider/file-shares/{key}+`

|===


== Aggiungere condivisioni di file

È possibile utilizzare il seguente metodo per aggiungere condivisioni di file CIFS e NFS nella SVM. Immettere i dettagli della condivisione file che si desidera creare, come parametri di input. Non è possibile utilizzare questa API per la creazione di FlexGroups.

[cols="1a,1a,1a"]
|===
| Categoria | Verbo HTTP | Percorso 


 a| 
provider di storage
 a| 
POST
 a| 
`/storage-provider/file-shares`

|===
[NOTE]
====
A seconda che siano forniti i parametri dell'elenco di controllo di accesso (ACL) o i parametri dei criteri di esportazione, vengono create condivisioni CIFS o condivisioni file NFS. Se non si forniscono i valori per i parametri ACL, le condivisioni CIFS non vengono create e le condivisioni NFS vengono create per impostazione predefinita, fornendo l'accesso a tutti.

====


== Eliminare le condivisioni di file

Per eliminare una condivisione file specifica, è possibile utilizzare il metodo seguente. Per eliminare una determinata condivisione file, è necessario inserire la chiave di condivisione file come parametro di input.

[cols="1a,1a,1a"]
|===
| Categoria | Verbo HTTP | Percorso 


 a| 
provider di storage
 a| 
ELIMINARE
 a| 
`+/storage-provider/file-shares/{key}+`

|===


== Modificare le condivisioni di file

È possibile utilizzare il seguente metodo per modificare una condivisione file e aggiornarne le proprietà.

È necessario fornire la chiave di condivisione file per modificare una determinata condivisione file. Inoltre, è necessario immettere la proprietà che si desidera aggiornare, insieme al relativo valore.

[NOTE]
====
Tenere presente che è possibile aggiornare solo una proprietà a una singola chiamata di questa API. Per gli aggiornamenti multipli, è necessario eseguire questa API tante volte.

====
[cols="1a,1a,1a"]
|===
| Categoria | Verbo HTTP | Percorso 


 a| 
provider di storage
 a| 
PATCH
 a| 
`+/storage-provider/file-shares/{key}+`

|===