---
permalink: reporting/concept-understanding-reports.html 
sidebar: sidebar 
keywords:  
summary: I report visualizzano informazioni dettagliate su storage, rete, qualità del servizio e relazioni di protezione, aiutandoti a identificare e risolvere potenziali problemi prima che si verifichino. 
---
= Informazioni sui report
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I report visualizzano informazioni dettagliate su storage, rete, qualità del servizio e relazioni di protezione, aiutandoti a identificare e risolvere potenziali problemi prima che si verifichino.

È possibile scaricare i report in formato PDF o CSV (comma-Separated Values). Quando si personalizza una vista, è possibile salvarla con un nome univoco per un utilizzo futuro. È inoltre possibile pianificare l'esecuzione regolare di un report basato su tale visualizzazione e condividerlo con altri utenti.

È possibile gestire tutti i report pianificati dalla pagina Report Schedules.

[NOTE]
====
Per gestire i report, è necessario disporre del ruolo di amministratore dell'applicazione o di amministratore dello storage.

====