---
permalink: reporting/reference-types-of-reports.html 
sidebar: sidebar 
keywords:  
summary: Elenco completo di visualizzazioni e pagine di inventario disponibili come report personalizzabili, salvati, scaricati e pianificati. 
---
= Tipi di report
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Elenco completo di visualizzazioni e pagine di inventario disponibili come report personalizzabili, salvati, scaricati e pianificati.



== Report Active IQ Unified Manager

|===
| Tipo | Oggetto di storage o di rete 


 a| 
Capacità
 a| 
Cluster

Aggregati

Volumi

Qtree



 a| 
Salute
 a| 
Cluster

Nodi

Aggregati

VM di storage

Volumi

Condivisioni SMB/CIFS

Condivisioni NFS



 a| 
Performance
 a| 
Cluster

Nodi

Aggregati

VM di storage

Volumi

LUN

Spazi dei nomi NVMe

Interfacce di rete (LIF)

Porte



 a| 
Qualità del servizio
 a| 
Gruppi di policy QoS tradizionali

Gruppi di policy QoS adattivi

Gruppi di criteri Performance Service Level Objective



 a| 
Relazioni di protezione dei volumi (disponibili nella pagina volumi)
 a| 
Tutte le relazioni

Stato del trasferimento degli ultimi 1 mese

Tasso di trasferimento degli ultimi 1 mese

|===