---
permalink: performance-checker/reference-what-data-does-the-workload-analyzer-display.html 
sidebar: sidebar 
keywords: workload analyzer charts 
summary: 'La pagina dell"analizzatore del carico di lavoro visualizza informazioni sugli eventi correnti che potrebbero influire sul carico di lavoro, consigli per risolvere il problema che causa l"evento e grafici per l"analisi della cronologia delle performance e della capacità.' 
---
= Quali dati vengono visualizzati dall'analizzatore del carico di lavoro
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La pagina dell'analizzatore del carico di lavoro visualizza informazioni sugli eventi correnti che potrebbero influire sul carico di lavoro, consigli per risolvere il problema che causa l'evento e grafici per l'analisi della cronologia delle performance e della capacità.

Nella parte superiore della pagina, specificare il nome del carico di lavoro (volume o LUN) che si desidera analizzare e il periodo di tempo in cui si desidera visualizzare le statistiche. È possibile modificare l'intervallo di tempo in qualsiasi momento se si desidera visualizzare un periodo di tempo più breve o più lungo.

Le altre aree della pagina visualizzano i risultati dell'analisi e i grafici delle prestazioni e della capacità.

[NOTE]
====
I grafici dei carichi di lavoro per le LUN non forniscono lo stesso livello di statistiche dei grafici per i volumi, quindi noterai delle differenze durante l'analisi di questi due tipi di carichi di lavoro.

====
* *Area di riepilogo eventi*
+
Visualizza una breve panoramica del numero e dei tipi di eventi che si sono verificati nel periodo di tempo. Quando sono presenti eventi provenienti da diverse aree di impatto (ad esempio, performance e capacità), queste informazioni vengono visualizzate in modo da poter selezionare i dettagli per il tipo di evento a cui si è interessati. Fare clic sul tipo di evento per visualizzare un elenco dei nomi degli eventi.

+
Se si verifica un solo evento durante il periodo di tempo, viene visualizzato un elenco di suggerimenti per risolvere il problema per alcuni eventi.

* *Cronologia eventi*
+
Mostra tutte le occorrenze degli eventi durante l'intervallo di tempo specificato. Posizionare il cursore su ciascun evento per visualizzarne il nome.

+
Se si è arrivati a questa pagina facendo clic sul pulsante *Analyze Workload* (analizza carico di lavoro) dalla pagina Event Details (Dettagli evento), l'icona dell'evento selezionato appare più grande in modo da poter identificare l'evento.

* *Area grafici delle performance*
+
Visualizza i grafici relativi a latenza, throughput (IOPS e MB/s) e utilizzo (sia per il nodo che per l'aggregato) in base al periodo di tempo selezionato. È possibile fare clic sul collegamento View performance details (Visualizza dettagli sulle prestazioni) per visualizzare la pagina Performance Explorer (Esplora prestazioni) per il carico di lavoro nel caso si desideri eseguire ulteriori analisi.

+
** *Latency* Visualizza la latenza per il carico di lavoro. Il grafico dispone di tre viste che consentono di visualizzare la latenza totale, la latenza divisa per letture, scritture e altri processi e la latenza divisa per componente del cluster.
+
Vedere link:concept-cluster-components-and-why-they-can-be-in-contention.html["Componenti del cluster e perché possono essere in conflitto"] per una descrizione dei componenti del cluster visualizzati qui.

** *Throughput* visualizza sia IOPS che MB/s di throughput per il carico di lavoro. Il grafico dispone di due viste che consentono di visualizzare il throughput totale e il throughput suddiviso per letture, scritture e altri processi.
+
Questo grafico mostra anche le impostazioni della soglia massima e minima di throughput della qualità del servizio (QoS), se configurate, in modo da poter vedere dove il sistema potrebbe limitare intenzionalmente il throughput.

** *Utilization* Visualizza l'utilizzo sia per l'aggregato che per il nodo su cui viene eseguito il carico di lavoro. Da qui è possibile vedere se l'aggregato o il nodo sono sovrautilizzati, causando quindi un'elevata latenza. Quando si analizzano i volumi FlexGroup, nei grafici di utilizzo sono elencati più nodi e più aggregati.


* *Area del grafico della capacità*
+
Visualizza i grafici relativi alla capacità dei dati e alla capacità Snapshot degli ultimi un mese per il carico di lavoro.

+
Per i volumi, fare clic sul collegamento View Capacity Details (Visualizza dettagli capacità) per visualizzare la pagina Health Details (Dettagli stato) del carico di lavoro nel caso si desideri eseguire ulteriori analisi. I LUN non forniscono questo collegamento perché non esiste una pagina Health Details per le LUN.

+
** *Capacity View* visualizza lo spazio totale disponibile allocato per il carico di lavoro e lo spazio logico utilizzato (dopo tutte le ottimizzazioni NetApp).
** *Snapshot View* visualizza lo spazio totale riservato per le copie Snapshot e la quantità di spazio attualmente in uso. Tenere presente che i LUN non forniscono una vista Snapshot. Entrambi i grafici includono una stima del tempo rimanente prima che la capacità sia piena per questo carico di lavoro. Queste informazioni si basano sull'utilizzo storico e richiedono un minimo di 10 giorni di dati. Quando rimangono meno di 30 giorni di capacità, Unified Manager identifica lo storage come "`quasi pieno`".



