---
permalink: install-windows/task-upgrading-openjdk-on-windows-ocum.html 
sidebar: sidebar 
keywords: Active IQ Unified Manager 
summary: 'È possibile eseguire l"aggiornamento a una versione più recente di Java Runtime Environment (JRE) sul server Windows su cui è installato Unified Manager per ottenere le correzioni per le vulnerabilità di sicurezza.' 
---
= Aggiornamento di JRE
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire l'aggiornamento a una versione più recente di Java Runtime Environment (JRE) sul server Windows su cui è installato Unified Manager per ottenere correzioni per le vulnerabilità della sicurezza.



== Prima di iniziare

È necessario disporre dei privilegi di amministratore di Windows per il sistema su cui è installato Unified Manager.



== Fasi

. Accedere come utente amministratore sul computer host di Unified Manager.
. Scaricare la versione appropriata di Java (a 64 bit) dal sito JDK sul sistema di destinazione.
+
Ad esempio, scarica `openjdk-11_windows-x64_bin.zip` da `+http://jdk.java.net/11/+`.

. Utilizzare la console dei servizi Windows per arrestare i seguenti servizi di Unified Manager:
+
** Servizio di acquisizione NetApp Active IQ (Ocie-au)
** Servizio server di gestione NetApp Active IQ (Oncommandsvc)


. Espandere `zip` file.
. Copiare le directory e i file dal risultato `jdk` directory (ad esempio, `jdk-11.0.2` Nella posizione in cui è installato Java. Esempio: `C:\Program Files\NetApp\JDK\`
. Avviare i servizi di Unified Manager utilizzando la console dei servizi Windows:
+
** Servizio server di gestione NetApp Active IQ (Oncommandsvc)
** Servizio di acquisizione NetApp Active IQ (Ocie-au)



