---
permalink: install-windows/task-changing-the-jboss-password-on-windows.html 
sidebar: sidebar 
keywords:  
summary: 'È possibile creare una nuova password JBoss personalizzata per sovrascrivere la password predefinita impostata durante l"installazione. Questa attività è facoltativa, ma alcuni siti potrebbero richiedere questa funzionalità di protezione per sovrascrivere l"impostazione predefinita di installazione di Unified Manager. Questa operazione modifica anche la password utilizzata da JBoss per accedere a MySQL.' 
---
= Modifica della password JBoss
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare una nuova password JBoss personalizzata per sovrascrivere la password predefinita impostata durante l'installazione. Questa attività è facoltativa, ma alcuni siti potrebbero richiedere questa funzionalità di protezione per sovrascrivere l'impostazione predefinita di installazione di Unified Manager. Questa operazione modifica anche la password utilizzata da JBoss per accedere a MySQL.



== Prima di iniziare

* È necessario disporre dei privilegi di amministratore di Windows per il sistema su cui è installato Unified Manager.
* Devi avere la password per l'utente root MySQL.
* Devi essere in grado di accedere al servizio fornito da NetApp `password.bat` script nella directory `\Program Files\NetApp\essentials\bin`.




== Fasi

. Accedere come utente amministratore sul computer host di Unified Manager.
. Utilizzare la console dei servizi Windows per arrestare i seguenti servizi di Unified Manager:
+
** Servizio di acquisizione NetApp Active IQ (Ocie-au)
** Servizio server di gestione NetApp Active IQ (Oncommandsvc)


. Avviare `password.bat` script per avviare il processo di modifica della password: `C:\Program Files\NetApp\essentials\bin> password.bat resetJBossPassword`
. Quando richiesto, inserire la password dell'utente root MySQL.
. Quando richiesto, inserire la password utente JBoss corrente.
+
La password predefinita è `D11h1aMu@79%`.

. Quando richiesto, inserire la nuova password utente JBoss, quindi immetterla di nuovo per confermarla.
+
Quando vengono apportate le modifiche, vengono visualizzati dei messaggi di conferma, quindi viene richiesta un'ultima volta la nuova password utente JBoss.

. Inserire la nuova password utente JBoss ancora una volta.
. Al termine dello script, avviare i servizi di Unified Manager utilizzando la console dei servizi Windows:
+
** Servizio server di gestione NetApp Active IQ (Oncommandsvc)
** Servizio di acquisizione NetApp Active IQ (Ocie-au)


. Una volta avviati tutti i servizi, è possibile accedere all'interfaccia utente di Unified Manager.

