---
permalink: config/task-configuring-event-notification-settings.html 
sidebar: sidebar 
keywords:  
summary: 'È possibile configurare Unified Manager in modo che invii notifiche di avviso quando viene generato un evento o quando viene assegnato un evento a un utente. È possibile configurare il server SMTP utilizzato per inviare l"avviso e impostare vari meccanismi di notifica, ad esempio le notifiche di avviso possono essere inviate come e-mail o trap SNMP.' 
---
= Configurazione delle impostazioni di notifica degli eventi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare Unified Manager in modo che invii notifiche di avviso quando viene generato un evento o quando viene assegnato un evento a un utente. È possibile configurare il server SMTP utilizzato per inviare l'avviso e impostare vari meccanismi di notifica, ad esempio le notifiche di avviso possono essere inviate come e-mail o trap SNMP.



== Prima di iniziare

È necessario disporre delle seguenti informazioni:

* Indirizzo e-mail da cui viene inviata la notifica di avviso
+
L'indirizzo e-mail viene visualizzato nel campo "`da`" nelle notifiche di avviso inviate. Se non è possibile recapitarlo per qualsiasi motivo, questo indirizzo e-mail viene utilizzato anche come destinatario per la posta non recapitabile.

* Nome host del server SMTP, nome utente e password per accedere al server
* Nome host o indirizzo IP dell'host di destinazione trap che riceverà il trap SNMP, oltre alla versione SNMP, alla porta trap in uscita, alla community e ad altri valori di configurazione SNMP richiesti
+
Per specificare più destinazioni di trap, separare ciascun host con una virgola. In questo caso, tutte le altre impostazioni SNMP, ad esempio versione e porta trap in uscita, devono essere le stesse per tutti gli host dell'elenco.



È necessario disporre del ruolo di amministratore dell'applicazione o di amministratore dello storage.



== Fasi

. Nel riquadro di navigazione a sinistra, fare clic su *Generale* > *Notifiche*.
. Nella pagina *Notifiche*, configurare le impostazioni appropriate e fare clic su *Salva*.
+
[NOTE]
====
....
**If the From Address is pre-filled with the address "ActiveIQUnifiedManager@localhost.com", you should change it to a real, working email address to make sure that all email notifications are delivered successfully.
** If the host name of the SMTP server cannot be resolved, you can specify the IP address (IPv4 or IPv6) of the SMTP server instead of the host name.
....
====

